### PR TITLE
Add setting for disposable time between transfers

### PR DESCRIPTION
**Pull request by MichaelKutzner**
This adds an option to increase the time between transfers by a fixed duration. This setting can be used, if passengers want some time for orientation or to compensate small delays.

### CODE REVIEW

**Comment by felixguendling** [comment]
please rename disposable -> additional

the word disposable seems not like a good fit
https://www.thesaurus.com/browse/disposable

**Comment by MichaelKutzner** [comment]
~~Any suggestions for a better name?~~ _Thank you for the fast reply_
I'm also not sure, if the duration for the footpath should include this duration. Or if it should be split, e.g. `FOOTPATH (duration=X,  additional_time=Y)`

**Comment by felixguendling** [comment]
I guess the user expects that (footpath time + additional time) < (departure time - arrival time)

At least I would expect that.

**Comment by MichaelKutzner** [comment]
That was my intention, to make the footpath duration and additional time more obvious. But as I wrote, I'm not sure what format might be good to avoid possible confusion. I think, it might also depends on how the feature will be used.

**Pull request merged**
